<?php

namespace oeuvresBundle\Repository;

/**
 * AvancementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvancementsRepository extends \Doctrine\ORM\EntityRepository
{
	
		public function ChargeListe()
		{
	
			$query = $this->getEntityManager()
			->createQuery(
					'SELECT
					t.id,
					t.active,
					t.libelle,
					t.datecreateAt
					FROM oeuvresBundle:Avancements t order by t.libelle'
			);
			
			try {
				return $query->getResult();
			} catch (\Doctrine\ORM\NoResultException $e) {
				return null;
			}
	
		}
			
}
