<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompositionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompositionsRepository extends EntityRepository
{

	public function ChargeListe()
	{
		
		$aArbre=array();
		
			$query = $this->getEntityManager()
			->createQuery(
					'SELECT
					t.id,
					t.active,
					t.instruments_id,
					t.accompagnements_id,
					t.quantite,			
					t.datecreateAt
					FROM oeuvresBundle:Compositions t order by t.accompagnements_id'
			);
			
			try {
	
				$a=$query->getArrayResult();
					
				foreach ($a as $compo)
				{
					$acompo=array("id"=>$compo['id']
									,"active"=>$compo['active']
									,"instruments_id"=>$compo['instruments_id']
									,"accompagnements_id"=>$compo['accompagnements_id']
									,"quantite"=>$compo['quantite']
									,"datecreateAt"=>$compo['datecreateAt']
								
							
							);
					$aArbre[]=$acompo;
				}
								
											
			} catch (\Doctrine\ORM\NoResultException $e) {
			}
			
			return $aArbre;
				
	}
	
}
