<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompositeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompositeursRepository extends EntityRepository
{

	public function ChargeListe()
	{
		
			$query = $this->getEntityManager()
			->createQuery(
					'SELECT
					t.id,
					t.active,
					t.prenom,
					t.nom,
					t.nationalite,
					t.datenaiss,
					t.datedeces,
					t.datecreateAt
					FROM oeuvresBundle:Compositeurs t
					WHERE t.active=1 order by t.nom,t.prenom'
			);
			
			try {
				return $query->getResult();
			} catch (\Doctrine\ORM\NoResultException $e) {
				return null;
			}
		
	}
}
