<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionsRepository extends EntityRepository
{
	public function ChargeListe()
	{
		
		$aFonctions=array();
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT
				t.id,
				t.active,
				t.code,
				t.libelle,
				t.datecreateAt
				FROM oeuvresBundle:Fonctions t order by t.libelle'
		);
			
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
				
		return $aFonctions;
		
	}
	
	public function ChargeListeIds()
	{
	
	
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT	t.id FROM oeuvresBundle:Fonctions t'
		);
	
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	
	
	}	
	
	/**
	 *
	 * @param string $sCode
	 * @return number
	 */
	public function rechercheFonction($sCode)
	{
		$id=0;
			
		$sCode=$this->epure($sCode);
		
		$sCode=strtoupper($sCode);
		
		$sCode=substr($sCode, 0,10);
		
		$sCode=sprintf("%s",$sCode);
	
		$sql="SELECT
				t.id from oeuvresBundle:Fonctions t
				WHERE t.code = '".$sCode."'";
		
		$query = $this->getEntityManager()
		->createQuery(
				$sql
				);
			
		try {
			$aIds=$query->getResult();
			if(is_array($aIds) && count($aIds)>0)
			{
				foreach ($aIds as $kid=>$id)
				{
					$id=$id['id'];
				}
			}
		} catch (\Doctrine\ORM\NoResultException $e) {
			$id=0;
		}
	
	
		return $id;
	}
	/**
	 *
	 * @param int $id
	 * @return string
	 */
	public function rechercheLibelle(int $id)
	{
		$slib='';
		
		$sql="SELECT
				t.id,t.libelle from oeuvresBundle:Fonctions t
				WHERE t.id = ".$id;
		
		
		$query = $this->getEntityManager()
		->createQuery(
				$sql
				);
		
		try {
			$aIds=$query->getResult();
			
			if(is_array($aIds) && count($aIds)>0)
			{
				foreach ($aIds as $kid=>$o)
				{
					$slib=$o['libelle'];
				}
			}
		} catch (\Doctrine\ORM\NoResultException $e) {
			$slib='';
		}
		
		//die('resultat recherche oeuvresBundle:Fonctions '.$slib);
		
		return  $slib;
	}
	/**
	 *
	 */
	public function insertionFonction($sLib)
	{
	
		$idcree=0;
	
		$sCode=$sLib;
				
		$sCode=$this->epure($sCode);

		$sCode=strtoupper($sCode);
		
		$sCode=substr($sCode, 0,10);
		
		$nowUtc = new \DateTime( 'now',  new \DateTimeZone( 'UTC' ) );
		
		$sdate= $nowUtc->format('Y-m-d h:i:s');
		
		$conn=$this->getEntityManager()->getConnection();
	
		$dataArray=array('code'=>$sCode,'libelle'=>$sLib,'active'=>1
				,'datecreateAt'=>$sdate
				
		);
	
		try {
			$bOk=$conn->insert('Fonctions', $dataArray);
	
		} catch (\Doctrine\ORM\NoResultException $e) {
			die("Erreur ".$e->getMessage());
		}
	
		$idcree=$conn->lastInsertId();
	
		return $idcree;
	
	}
	
	private function epure($texte)
	{
		$texte = trim(strtolower($texte));
		$texte = htmlentities($texte, ENT_NOQUOTES, 'utf-8');
		$texte = preg_replace('#&([A-za-z])(?:acute|cedil|circ|grave|orn|ring|slash|th|tilde|uml);#', '\1', $texte);
		$texte = preg_replace('#&([A-za-z]{2})(?:lig);#', '\1', $texte); // pour les ligatures
		$texte = preg_replace('#&[^;]+;#', '', $texte); // supprime les autres caractères
		$texte = preg_replace('#&[^;]+;#', '', $texte); // supprime les autres caractères
		
		$texte = strtr(
				$texte,
				'@ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïðòóôõöùúûüýÿ',
				'aAAAAAACEEEEIIIIOOOOOUUUUYaaaaaaceeeeiiiioooooouuuuyy'
				);
		
		
		return $texte;
	}
	
}
