<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionsRepository extends EntityRepository
{
	public function ChargeListe()
	{
		
		$aFonctions=array();
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT
				t.id,
				t.active,
				t.code,
				t.libelle,
				t.datecreateAt
				FROM oeuvresBundle:Fonctions t order by t.libelle'
		);
			
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
				
		return $aFonctions;
		
	}
	
	public function ChargeListeIds()
	{
	
	
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT	t.id FROM oeuvresBundle:Fonctions t'
		);
	
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	
	
	}	
}
