<?php

namespace oeuvresBundle\Repository;

/**
 * InstrumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstrumentsRepository extends \Doctrine\ORM\EntityRepository
{
	
		public function ChargeListe()
		{
	
			$query = $this->getEntityManager()
			->createQuery(
					'SELECT
					t.id,
					t.active,
					t.libelle,
					t.datecreateAt
					FROM oeuvresBundle:Instruments t order by t.libelle'
			);
				
			try {
				return $query->getResult();
			} catch (\Doctrine\ORM\NoResultException $e) {
				return null;
			}
				
		}
			
}
