<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LoginsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginsRepository extends EntityRepository
{

	public function ChargeListe()
	{
		
		$aLogins=array();
			
		return $aLogins;
		
	}
}
