<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartitionsRepository extends EntityRepository
{
	
	public function ChargeListe()
	{
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT
				t.id,
				t.active,
				t.oeuvre_id,		
				t.libelle,
				t.datecreateAt
				FROM oeuvresBundle:Partitions t
				WHERE t.active=1'
		);
		
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
		
	}
	

		
}
