<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilsRepository extends EntityRepository
{
	
	public function ChargeListe()
	{
		$query = $this->getEntityManager()
		->createQuery(
				"SELECT
				t.id,
				t.CodeProfil,
				t.libelleProfil,
				t.actif,
				t.datecreateAt
				FROM oeuvresBundle:Profils t order by t.libelleProfil"
		);
		
		//				WHERE t.actif=1"
		
		
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
		
	}
	/**
	 *
	 * @param string $sCode
	 * @return number
	 */
	public function rechercheProfil($id)
	{
		
		$sql="SELECT
				t.id,t.libelleProfil from oeuvresBundle:Profils t
				WHERE t.id = ".$id;
		
		$query = $this->getEntityManager()
		->createQuery(
				$sql
				);
		$s='profil inconnu';
		try {
			$aIds=$query->getResult();
			if(is_array($aIds) && count($aIds)>0)
			{
				foreach ($aIds as $kid=>$opro)
				{
					$s=$opro['libelleProfil'];
				}
			}
		} catch (\Doctrine\ORM\NoResultException $e) {
			$s='pb';
		}
		
		return $s;
	}

}
