<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilsRepository extends EntityRepository
{
	
	public function ChargeListe()
	{
		$query = $this->getEntityManager()
		->createQuery(
				"SELECT
				t.id,
				t.CodeProfil,
				t.libelleProfil,
				t.actif,
				t.datecreateAt
				FROM oeuvresBundle:Profils t order by t.libelleProfil"
		);
		
		//				WHERE t.actif=1"
		
		
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
		
	}
}
