<?php

namespace oeuvresBundle\Repository;

use Doctrine\DBAL\Driver\PDOConnection;

use Doctrine\DBAL\Driver\PDOSqlite\Driver;

use Doctrine\ORM\EntityRepository;

//use \Doctrine\DBAL\Driver\Mysqli\MysqliConnection;

use Doctrine\ORM\Persisters\BasicEntityPersister;

/**
 * SouscategvoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscategvoixRepository extends EntityRepository
{

	public function ChargeListe()
	{
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT
				t.id,
				t.voix_id,
				t.active,
				t.libelle,
				t.datecreateAt
				FROM oeuvresBundle:Souscategvoix t
				 order by t.libelle'
		);
			
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
				
	}
	
	public function ChargeListeSsCategVoix($voix_id)
	{
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT
				t.id,
				t.voix_id,
				t.active,
				t.libelle,
				t.datecreateAt
				FROM oeuvresBundle:Souscategvoix t
				WHERE t.voix_id='.$voix_id.' order by t.libelle'
		);
			
		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
