<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypesmusiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesmusiquesRepository extends EntityRepository
{
	
	public function ChargeListe()
	{
		
		
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT
				t.id,
				t.active,
				t.libelle,
				t.datecreateAt
				FROM oeuvresBundle:Typesmusiques t
				ORDER BY t.libelle'
		);
				
		try {				
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
		
		
	}
	
	/**
	 *
	 */
	public function insertionTypedemusique($id,$sLibelle)
	{
		
		$idcree=0;
		
		$sLibelle=trim($sLibelle);
		
		$conn=$this->getEntityManager()->getConnection();
		
		$nowUtc = new \DateTime( 'now',  new \DateTimeZone( 'UTC' ) );
		
		$s= $nowUtc->format('Y-m-d h:i:s');
		
		$dataArray=array('id'=>$id,'libelle'=>$sLibelle
				,'active'=>1
				,'datecreateAt'=>$s
		);
		//echo "<br/>insertionTypedemusique >".$sLibelle."<";
		try {
			$bOk=$conn->insert('Typesmusiques', $dataArray);
			
		} catch (\Doctrine\ORM\NoResultException $e) {
			die("Erreur ".$e->getMessage());
		}
		
		$idcree=$conn->lastInsertId();
		
		return $idcree;
		
	}
	
	
}
