<?php

namespace oeuvresBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypesmusiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesmusiquesRepository extends EntityRepository
{
	
	public function ChargeListe($aFiltres=null)
	{
		$btous=true;
		$stypesmusique='';
		if(isset($aFiltres) & is_array($aFiltres) & count($aFiltres)!=0)
		{
			$stypesmusique=(isset($aFiltres['typesmusique'])) ? $aFiltres['typesmusique'] : '';
			$btous=(isset($aFiltres['tous'])) ? $aFiltres['tous'] : 0 ;
			$btous=!($btous==0);
		}
		
		$sSql='SELECT
				t.id,
				t.active,
				t.libelle,
				t.datecreateAt
				FROM oeuvresBundle:Typesmusiques t WHERE t.active=1';
		
		if(!$btous && $stypesmusique!='')
		{
			$s=sprintf("%s",$stypesmusique);
			$sSql.=" and (t.libelle like '%$s%'";
			$sSql.=" or t.libelle = '$stypesmusique')";
		}
		
		$sSql.=' ORDER BY t.libelle';
		
		$query = $this->getEntityManager()
		->createQuery($sSql);
				
		try {				
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
		
		
	}
	
	/**
	 *
	 */
	public function insertionTypedemusique($id,$sLibelle)
	{
		
		$idcree=0;
		
		$sLibelle=trim($sLibelle);
		
		$conn=$this->getEntityManager()->getConnection();
		
		$nowUtc = new \DateTime( 'now',  new \DateTimeZone( 'UTC' ) );
		
		$s= $nowUtc->format('Y-m-d h:i:s');
		
		$dataArray=array('id'=>$id,'libelle'=>$sLibelle
				,'active'=>1
				,'datecreateAt'=>$s
		);
		//echo "<br/>insertionTypedemusique >".$sLibelle."<";
		try {
			$bOk=$conn->insert('Typesmusiques', $dataArray);
			
		} catch (\Doctrine\ORM\NoResultException $e) {
			die("Erreur ".$e->getMessage());
		}
		
		$idcree=$conn->lastInsertId();
		
		return $idcree;
		
	}
	
	
}
